### ISSUE TITLE
Update to 2.11.2

### ISSUE THREAD

**Issue by koppor** [BenjaminHae/choco-packages#3]
The package should be updated to 2.11.2 (which was [released yesterday](http://www.texstudio.org/#news)).

The package source on this repo shows `<version>2.10.4</version>`, but on https://chocolatey.org/packages/texstudio, version 2.11.0 is listed. Is this really the right repository linked at "package source"? Is the current package source https://github.com/aronovgj/choco-auto/tree/master/texstudio @aronovgj?

**Comment by BenjaminHae** [comment]
This repo isn't active anymore. aronovgj took over. But I don't know where his source is.

**Comment by koppor** [comment]
Could you add that to the README.md? 😇
